# Generated by Django 5.2.8 on 2025-11-24 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimaDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('humedad', models.CharField(max_length=45)),
                ('radiacion_solar', models.CharField(max_length=45)),
                ('condicion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_especie', models.CharField(max_length=45, verbose_name='Nombre de la Especie')),
                ('factor_conversion', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Factor de Conversión (Húmedo:Seco)')),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_zona', models.CharField(max_length=45, verbose_name='Nombre de la Zona')),
                ('ubicacion', models.CharField(max_length=45, verbose_name='Ubicación Geográfica')),
            ],
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=45, verbose_name='Tipo de Alerta')),
                ('mensaje', models.CharField(max_length=255)),
                ('nivel', models.CharField(choices=[('CRITICA', 'Crítica'), ('ADVERTENCIA', 'Advertencia')], max_length=45)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('en_mail', models.BooleanField(default=False, verbose_name='Notificado por Email')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_humedo_inicial', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso Húmedo Inicial (kg)')),
                ('peso_seco_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso Seco Final (kg)')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Proyeccion.especie')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Proyeccion.zona')),
            ],
        ),
        migrations.CreateModel(
            name='InventarioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad Disponible (kg)')),
                ('estado', models.CharField(choices=[('VIVO', 'Vivo (en cultivo)'), ('SECO', 'Seco (terminado)'), ('PROCESO', 'En Proceso de Secado')], default='VIVO', max_length=45)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Proyeccion.especie')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Proyeccion.lote')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Proyeccion.zona')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('FACTIBLE', 'Factible'), ('RIESGO', 'En Riesgo de Incumplimiento'), ('COMPLETADO', 'Completado')], default='PENDIENTE', max_length=45)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Ejecutivo Comercial')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volumen_en_seco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Volumen Seco Requerido (kg)')),
                ('granulometria', models.CharField(max_length=45)),
                ('estado', models.CharField(default='PENDIENTE', max_length=45)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Proyeccion.especie')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proyeccion.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('PLANTA', 'Gerente de Planta'), ('CULTIVO', 'Coordinador de Cultivo'), ('COMERCIAL', 'Ejecutivo Comercial'), ('AUDITOR', 'Auditor / Invitado')], default='CULTIVO', max_length=45)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proyeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias', models.IntegerField(choices=[(7, '7 días'), (14, '14 días')])),
                ('capacidad_estimada', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Capacidad Estimada (kg)')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Proyeccion.especie')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_reservada', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad Reservada (kg)')),
                ('estado_reserva', models.CharField(default='RESERVADO', max_length=45)),
                ('fecha_reserva', models.DateField(auto_now_add=True)),
                ('inventarioitem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Proyeccion.inventarioitem')),
                ('pedidodetalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proyeccion.pedidodetalle')),
            ],
        ),
    ]
